### PR TITLE
Fix ntp/osc timestamp/timetag conversion and TimedMessage time.

### PR DESCRIPTION
**Pull request by smrg-lm**
Hi

OSC timetag conversion was broken. This PR solves that problem and TimedMessage not being scheduled from bundles by Dispatcher.call_handlers_for_packet().

I did change some names to make them more meaningful (at least for me). If that is not acceptable you can still take the timing fix from this patch and have my approval.

### CODE REVIEW

**Comment by attwad** [comment]
Thanks for the PR, overall that's much cleaner, please fix the failing tests (and add more if necessary), then we can merge. 👍

**Comment by smrg-lm** [comment]
Ok, tests are good, I have the tests passing now but found an issue, will try improve it and come back.

**Comment by smrg-lm** [comment]
Done. There are some things about naming and used data types (IMO) but I didn't review all the library, just picked the ones used by module trying to follow the style.

**Comment by attwad** [comment]
Much appreciated, merging now.

**Pull request merged**
