### PR TITLE
Fix install of pygame on Python 3.11

### PR DESCRIPTION
**Pull request by PeterJCLaw**
See https://github.com/pygame/pygame/issues/3522#issuecomment-1293981862.

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
CI failures are due to `mypy` issues, which are explored separately in #161

**Comment by attwad** [comment]
3.7 seems to be unhappy about that change no?
https://github.com/attwad/python-osc/actions/runs/3487223249/jobs/5834596260

**Comment by PeterJCLaw** [comment]
Hrm, I'm not sure there's a version of pygame which supports old and new Python :(
Pinning mypy for now is looking more appealing.

**Comment by PeterJCLaw** [comment]
Ok, I think `pygame` is happy now -- we're back to the original `mypy` errors I think.

**Pull request merged**
