### PR TITLE
Correctly set the message type for booleans

### PR DESCRIPTION
**Pull request by Yamakaky**
```
>>> isinstance(True, int)
True
```
 
See https://stackoverflow.com/questions/37888620/python-comparing-boolean-and-int-using-isinstance

### CODE REVIEW

**Comment by attwad** [comment]
Thanks!

**Comment by Yamakaky** [comment]
That was quick ^^
Do you know when it should be released?

**Comment by attwad** [comment]
I'll push a release in the next ~12h

**Comment by attwad** [comment]
Done.
https://pypi.python.org/pypi/python-osc/1.6.5

**Comment by Yamakaky** [comment]
Nice!

**Comment by attwad** [comment]
My review was hasty, this breaks integers and floats sorry I'll rollback the change.

**Comment by Yamakaky** [comment]
Hum, I didn't try, why does it?

**Comment by attwad** [comment]
Almost anything in python evaluates to True, so non zero integers/floats were interpreted as booleans
https://github.com/attwad/python-osc/issues/57

**Comment by Yamakaky** [comment]
Hum, I see. Maybe then use `left is True`? I think `True` and `False` are guaranteed to be singletons (to be checked)

**Comment by Yamakaky** [comment]
In any case, time to write some tests XD

**Pull request merged**
