### PR TITLE
Add Debian packaging

### PR DESCRIPTION
**Pull request by m-roberts**

### CODE REVIEW

**Comment by dvzrv** [comment]
Why is this not maintained with the distribution though? It makes no sense for an upstream to maintain their own packaging build scripts (unless they want to explicitly provide prebuilt packages in a custom repository). That's what distributions are for.

You could ask the responsible teams in the respective distributions to package it (e.g. multimedia team with debian or fedora).

**Comment by attwad** [comment]
Thank you for the PRs. Can you please explain why having a debian package is better than relying on pip or whatever package manager you prefer to install this library? I'm trying to keep things simple here as I maintain this on a best effort and I'm definitely not versed in debian packaging hence my question, thank you.

**Comment by m-roberts** [comment]
> Why is this not maintained with the distribution though? It makes no sense for an upstream to maintain their own packaging build scripts (unless they want to explicitly provide prebuilt packages in a custom repository). That's what distributions are for.
> 
> You could ask the responsible teams in the respective distributions to package it (e.g. multimedia team with debian or fedora).

We have this hosted on our fork, and will be using that as the basis for our own distribution if upstream does not want to manage additional packaging. However, I wanted to offer the chance to review the code change - hence this PR!



> Thank you for the PRs. Can you please explain why having a debian package is better than relying on pip or whatever package manager you prefer to install this library? I'm trying to keep things simple here as I maintain this on a best effort and I'm definitely not versed in debian packaging hence my question, thank you.

On Debian-based systems, it is encouraged to make use of Debian packages for Python modules where possible.

The best case scenario would be that this packaging gets accepted by the team at Debian, Ubuntu, etc. that would be responsible for maintaining it in their repository for their particular distribution.

For users like myself, easily being able to package a Python module for Debian-based operating is much appreciated!

The actual maintenance is pretty low - just the changelog needs to be updated with a new release. Given that this is a mature, stable offering, it seems that this will be infrequent at most.

It's really up to you whether you want to handle it or not. You could, if you wish, direct people to our fork if they are looking for a Debian package for the module. Unfortunately, we wouldn't be able to guarantee keeping it up-to-date in the same way as if it were included as an additional build artifact alongside the Python wheel.

**Comment by m-roberts** [comment]
The simplest way to support building the Debian package in CI should be as simple as including the [`action-debian-package`](https://github.com/dawidd6/action-debian-package) action in a GitHub Actions workflow.

**Comment by m-roberts** [comment]
You may also prefer simply directing users to our own hosting of these packages: https://github.com/pi-top/python-osc-deb

**Pull request closed without merging**
